name: solana_web3
description: The Solana Dart API built on Solana's JSON RPC API, with support for common Native Programs.
version: 0.0.3
repository: https://github.com/merigo-labs/solana-web3
issue_tracker: https://github.com/merigo-labs/solana-web3/issues/new/choose

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  async: ^2.8.2
  base_codecs: ^1.0.1
  connectivity_plus: ^3.0.2
  crypto: ^3.0.2
  http: ^0.13.5
  pinenacl: ^0.5.1
  solana_common: ^0.0.2 
    # path: ../solana_common
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.